version: "3.9"
services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: testcontainers
      POSTGRES_DB: testcontainers_demo
